### ISSUE TITLE
Some M19 lands are 403ing

### ISSUE THREAD

**Issue by dhouck** [Sylencia/landcycler#5]
For Plains, Island, and Swamp, the first one shows up correctly and then the next three give 403 errors. In particular, Plains 262, 263, and 264; Island 266, 267, and 268; and Swamp 270, 271, and 272 are all not showing up.

**Comment by Sylencia** [comment]
Thanks for letting me know, I was planning on updating it but got distracted with actually playing MTG:A over the weekend. I'll get it done tonight or tomorrow.

**Comment by Sylencia** [comment]
Land data has now also been updated. Thanks for using the site!
